### PR TITLE
Minor fixes for 4.0.0 release

### PR DESCRIPTION
**Pull request by HaydarAk**
- update ontology and shacl

### CODE REVIEW

**Comment by clange** [comment]
In codes/Action.ttl it would make sense to use the name `idsc:TRACK_PROVENANCE`, as the other multi-word action names also use underscores.

**Comment by clange** [comment]
@HaydarAk let me continue to note down minor issues during the review of #331 here:
* `/Shacl.ttl` and possibly other files still use the old repository URL "IndustrialDataSpace".

**Comment by clange** [comment]
* `codes/SecurityGuarantee.ttl` describes `idsc:TRUST_SECURITY_PROFILE` as "The Security Profile TRUST as defined by the IDS certification criteria." This should be backed by a triple `... rdfs:isDefinedBy <https://www.internationaldataspaces.org/wp-content/uploads/2020/01/IDSA-Strategy-paper-certification-scheme-V.2.pdf>`. In a second step (could you please turn that into a separate issue) we might create separate resources in the infomodel in order to be able to properly "cite" such authoritative sources of definitions. (Of course, the home of any such definitions within the IDS Universe should be IDS-G; cf. #266.)

**Comment by clange** [comment]
* I thought we had even explained in the Changelog that media types should now use the IANA URLs but additionally be declared explicitly as instances of, e.g., `ids:IANAMediaType` in order to validate. However, `examples/APP_RESOURCE.jsonld` does not do so.

**Comment by HaydarAk** [comment]
> * I thought we had even explained in the Changelog that media types should now use the IANA URLs but additionally be declared explicitly as instances of, e.g., `ids:IANAMediaType` in order to validate. However, `examples/APP_RESOURCE.jsonld` does not do so.

It does. Because the JSONLD example for app resource is generated by a RDF converter it looks rather cryptic. Line 20-21 defines the `https://www.iana.org/assignments/media-types/application/zip` as a IANAMediaType and line 31-32 uses this id for the appRepresentation.

**Comment by clange** [comment]
* Do we still need `examples/DATA3.ttl`? I think it was used to demonstrate functionality that we have now deleted from the infomodel. The few lines that remain in the example are no longer particularly instructive, so I think it can be removed.

**Comment by clange** [comment]
* Why is `examples/TEXT_RESOURCE.json` not named `*.jsonld`? (Maybe there are further files that should be renamed?)

**Comment by clange** [comment]
* The naming of `examples/contracts-and-usage-policy/templates/ConnectorbasedAgreementTemplates/CONNECTORBASED_REQUEST_TEMPLATE.ttl` and some of its resources/classes does not look right to me. Why is it not `ConnectorBased...` and `CONNECTOR_BASED_...`?

**Comment by clange** [comment]
* `examples/contracts-and-usage-policy/templates/EventRestrictedUsage/EVENT_OFFER_TEMPLATE.jsonld` mentions a type `http://www.w3.org/2001/XMLSchema#:boolean`, i.e., containing a spurious colon.

**Comment by clange** [comment]
* BTW speaking of types, e.g., in `examples/contracts-and-usage-policy/templates/EventRestrictedUsage/EVENT_OFFER_TEMPLATE.ttl`: In Turtle, one can simply write `true` instead of `"true"^^xsd:boolean`.

**Comment by clange** [comment]
* In `examples/contracts-and-usage-policy/templates/RentalTemplates/RENTAL_AGREEMENT_TEMPLATE.ttl` is the "wrong" syntax `"?fee"^^xsd:double` intended, i.e., to express that the type of this variable should be double?

**Pull request merged**
