### PR TITLE
Feature/examples4iswc

### PR DESCRIPTION
**Pull request by HaydarAk**

### CODE REVIEW

**Review by clange — COMMENTED** [review]
Not sure why "role based offer/request template" is part of this PR, but it all looks good to me.

**Review by clange — APPROVED** [review]
Looks good. Before merging please check where the examples are still up to date w.r.t. the latest version of the infomodel.

**Review by sebbader — APPROVED** [review]

**Comment by sebbader** [comment]
Quite embarrassing that I have missed this PR for so long. Fine with me though. @HaydarAk will you merge it?

**Comment by HaydarAk** [comment]
We (I) should run a SHACL validation on these files. Although there should be no breaking changes, we might have some bugfixes as part of the latest patches / releases

**Pull request closed without merging**
