### PR TITLE
Document version mapping

### PR DESCRIPTION
**Pull request by JohannesLipp**
Add further documentation on version mapping for 300->310 as well as 310->400. This includes both Word/Excel documentation and example files. 

Relates to #312 and #344

### CODE REVIEW

**Review by clange — CHANGES_REQUESTED** [review]
Largely good but could someone please rename `blacklist-shapes-440` to `blacklist-shapes-400` before merging?

**Comment by JohannesLipp** [comment]
I renamed the file as suggested, thank you @clange . This PR can be merged by anyone with sufficient permissions, e.g. you :)

**Review by HaydarAk — APPROVED** [review]

**Comment by JohannesLipp** [comment]
@clange I applied your requested change and @HaydarAk also approved. Please do another review and approve/merge if possible - thanks!

**Comment by JohannesLipp** [comment]
> @clange I applied your requested change and @HaydarAk also approved. Please do another review and approve/merge if possible - thanks!

@clange Push

**Review by clange — APPROVED** [review]
Thank you, looks good

**Pull request merged**
