### PR TITLE
Application Profile for DCAT (DCAT-AP) Following European Best Practices

### PR DESCRIPTION
**Pull request by JohannesLipp**
As described in #277 , we would strongly benefit from an alignment with a widely-used DCAT-AP such as the [DCAT Application Profile for data portals in Europe](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/release/200).

This pull requests adds adopted SHACL shapes for validation. Its content (=validation constraints) should be discussed and evaluated for strict usage in the IDS.

### CODE REVIEW

**Review by clange — COMMENTED** [review]
Looks good. Sorry that this remained unreviewed for such a long time.

**Review by clange — APPROVED** [review]
With my previous comment I actually meant to approve. Here is, however, one request for discussion: having these shapes is nice, but there should also a way to (optionally?) instruct the Java library to enforce them, whenever it's used in a setting where DCAT-AP conformance is required.

**Comment by JohannesLipp** [comment]
> With my previous comment I actually meant to approve. Here is, however, one request for discussion: having these shapes is nice, but there should also a way to (optionally?) instruct the Java library to enforce them, whenever it's used in a setting where DCAT-AP conformance is required.

@maboeckmann Could you briefly comment if the Java library enforces compatibility with existing SHACL shapes? If so, then @clange you could create a new issue for this. Thank you.

**Comment by maboeckmann** [comment]
Yes, the code itself already includes some requirements, e.g. whether fields are mandatory or can occur multiple times. On top of that, we created a full-fledged SHACL validator, which is however not included in the Java model classes and is therefore optional.

**Pull request merged**
