### PR TITLE
fix typo and remove leftover IDS terms in ODRL examples

### LINKED ISSUE #598: Fix typos and obsolete IDS terms in ODRL examples
e.g. "DistributeEcryptedAgreement" and leftover usages of IDS terms, which had been dropped by #504 / #543 in favour of plain ODRL

### PR DESCRIPTION
**Pull request by clange**
fixes #598

### CODE REVIEW

**Review by lcomet — APPROVED** [review]
Fixed typo: ok

**Review by lcomet — APPROVED** [review]
replacement of ids:Duty by odrl:Duty in json and jsonld files: ok

**Review by lcomet — APPROVED** [review]
odrl properties instead of ids, ok.

**Review by lcomet — APPROVED** [review]
ok

**Review by lcomet — APPROVED** [review]

**Review by lcomet — APPROVED** [review]

**Review by lcomet — APPROVED** [review]

**Review by lcomet — APPROVED** [review]

**Review by lcomet — APPROVED** [review]

**Review by lcomet — APPROVED** [review]

**Review by lcomet — APPROVED** [review]
changes ok

**Review by JohannesLipp — APPROVED** [review]
Good approach. Also good changes to the c&p flaws in Contract.ttl

**Pull request merged**
